### ISSUE TITLE
Jenkins 2.54 now depends on Java 8

### ISSUE THREAD

**Issue by marksutherland** [geerlingguy/ansible-role-jenkins#129]
Hi,

I've been observing the following error over the last day or two when running this playbook via vagrant:

```
fatal: [dev]: FAILED! => {"attempts": 60, "changed": false, "cmd": "curl -D - --silent --max-time 5 http://localhost:8080/cli/", "delta": "0:00:00.014382", "end": "2017-04-12 09:34:34.775059", "failed": true, "rc": 0, "start": "2017-04-12 09:34:34.760677", "stderr": "", "stdout": "HTTP/1.1 503 Service Unavailable\r\nDate: Wed, 12 Apr 2017 09:34:34 GMT\r\nCache-Control: must-revalidate,no-cache,no-store\r\nContent-Type: text/html; charset=ISO-8859-1\r\nContent-Length: 292\r\nServer: Jetty(9.2.z-SNAPSHOT)\r\n\r\n<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/>\n<title>Error 503 </title>\n</head>\n<body>\n<h2>HTTP ERROR: 503</h2>\n<p>Problem accessing /cli/. Reason:\n<pre>    Service Unavailable</pre></p>\n<hr /><i><small>Powered by Jetty://</small></i>\n</body>\n</html>", "stdout_lines": ["HTTP/1.1 503 Service Unavailable", "Date: Wed, 12 Apr 2017 09:34:34 GMT", "Cache-Control: must-revalidate,no-cache,no-store", "Content-Type: text/html; charset=ISO-8859-1", "Content-Length: 292", "Server: Jetty(9.2.z-SNAPSHOT)", "", "<html>", "<head>", "<meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/>", "<title>Error 503 </title>", "</head>", "<body>", "<h2>HTTP ERROR: 503</h2>", "<p>Problem accessing /cli/. Reason:", "<pre>    Service Unavailable</pre></p>", "<hr /><i><small>Powered by Jetty://</small></i>", "</body>", "</html>"], "warnings": ["Consider using get_url or uri module rather than running curl"]}
```

Looking in the jenkins log file I can see the following traceback:

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85)
        at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72)
        at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:408)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1340)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at winstone.Launcher.<init>(Launcher.java:152)
        at winstone.Launcher.main(Launcher.java:352)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at Main._main(Main.java:264)
        at Main.main(Main.java:112)
Caused by: java.lang.UnsupportedClassVersionError: jenkins/util/SystemProperties : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:510)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:441)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403)
        at org.eclipse.jetty.server.handler.ContextHandler.loadClass(ContextHandler.java:1583)
        at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1956)
        ... 25 more
```

Which eventually led me to this JIRA ticket that makes it clear the latest jenkins now needs java 8.

https://issues.jenkins-ci.org/browse/JENKINS-43492

I'm deploying on debian jessie, so my current plan is to add the backports repository and set the java_packages variable to pick up 1.8. I'm not sure that's the best solution for the role overall though.

**Comment by geerlingguy** [comment]
@marksutherland - You should probably do something like what my Sonar role does (SonarQube also requires Java 8 now): https://github.com/geerlingguy/ansible-role-sonar/blob/master/tests/test-latest.yml

I'm guessing the tests for this role may need updating as well, to make sure things work correctly with the latest versions.

**Comment by marksutherland** [comment]
Here's what I've gone with. I was hoping to handle it all outside the role, but unfortunately the java 8 package from jessie-backports doesn't update the java alternative, and the certificates package pulls in java 7. As a result, I've had to add an extra task to setup-Debian.yml.

Main playbook:
```
- hosts: dev
  pre_tasks:
    - name: Add jessie-backports repo
      apt_repository:
        repo: deb http://httpredir.debian.org/debian jessie-backports main
        state: present
    - name: Install java certificates from backports
      apt:
        name: ca-certificates-java
        default_release: jessie-backports
        state: installed
  vars:
    - java_packages:
      - openjdk-8-jdk
  roles:
    - geerlingguy.jenkins
```

In setup-Debian.yml before jenkins is installed.
```
- name: Ensure java version used is java 8
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java 
```

I'll try the ppa and see if it sets the alternatives correctly. Thanks!

**Comment by marksutherland** [comment]
Ok, doesn't look like I can use the ppa with debian jessie.

**Comment by yakhyadabo** [comment]
Is there any way to set the version of Jenkins to avoid having this issue ?

**Comment by yakhyadabo** [comment]
In there any jenkins role which doesn't require java at all ?

**Comment by geerlingguy** [comment]
@yakhyadabo - Yes, see https://github.com/geerlingguy/ansible-role-jenkins/blob/master/defaults/main.yml#L4-L5

And see https://github.com/geerlingguy/ansible-role-jenkins/blob/master/tests/test-jenkins-version.yml for an example that's built on Travis CI.

**Comment by yakhyadabo** [comment]
Ok setting the Jenkins version to 2.53 solves the issue for me. 

Thanks

**Comment by geerlingguy** [comment]
...aaaand now tests are failing too. I'll have to at least get all the test rigs upgraded to Java 8 :)

**Comment by geerlingguy** [comment]
See updated README and the tests in the `tests/` folder.

Also, opening follow-up: https://github.com/geerlingguy/ansible-role-jenkins/issues/130
