### ISSUE TITLE
Validate/installation task causing initial failure consistently

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-jenkins#150]
I seem to be getting this error consistently on the first-time execution of this role.

Re-running it works fine, but it happens consistently on Ubuntu 12.04 and Ubuntu 16.04.

```
TASK [geerlingguy.jenkins : Validate Jenkins is installed and register package name.] ***
ERROR! Unexpected Exception: 'a45e60e1-1259-7b77-e3a6-0000000029b1'
to see the full traceback, use -vvv
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again
```

**Comment by geerlingguy** [comment]
Interesting; @fubarhouse - What version of the role are you currently using? I can't seem to find that task in the current version and I don't remember how it worked in older versions of the role. It might just be that you need to update the role and that error will stop happening.

**Comment by fubarhouse** [comment]
I honestly don't know, but I'll update it and see how that goes and let you know.

**Comment by fubarhouse** [comment]
So the version in use is actually rather behind the master branch...
The version is pinned at 2.14, if that is anything to go by, there is no other indication to the version of the role as it is maintained within a private fork of DrupalVM.

With that said, I'll attempt to spin up another vm today or tomorrow with the newly updated role.

**Comment by fubarhouse** [comment]
Just tested the latest version and it causes the same thing, I'll do it again and provide some verbose output today.

**Comment by geerlingguy** [comment]
Thanks!

**Comment by fubarhouse** [comment]
Here you are! Done via your Ubuntu 16.04 vagrant box.

```
TASK [geerlingguy.jenkins : Ensure Jenkins is installed.] **********************
task path: /Users/education/vagrant/acquia-goci-education/provisioning/roles/geerlingguy.jenkins/tasks/setup-Debian.yml:39
Using module file /Library/Python/2.7/site-packages/ansible/modules/packaging/os/apt.py
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2200 -o 'IdentityFile="/Users/education/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/education/.ansible/cp/17d6e21220 127.0.0.1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<127.0.0.1> (0, '/home/vagrant\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 68578\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2200 -o 'IdentityFile="/Users/education/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/education/.ansible/cp/17d6e21220 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673 `" && echo ansible-tmp-1500347705.21-36095657481673="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673 `" ) && sleep 0'"'"''
<127.0.0.1> (0, 'ansible-tmp-1500347705.21-36095657481673=/home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 68578\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> PUT /var/folders/d0/5b415g_d1nld6ygg0sbqvsv40000gn/T/tmp_Vq_AN TO /home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673/apt.py
<127.0.0.1> SSH: EXEC sftp -b - -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2200 -o 'IdentityFile="/Users/education/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/education/.ansible/cp/17d6e21220 '[127.0.0.1]'
<127.0.0.1> (0, 'sftp> put /var/folders/d0/5b415g_d1nld6ygg0sbqvsv40000gn/T/tmp_Vq_AN /home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673/apt.py\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 68578\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 8 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/vagrant size 0\r\ndebug3: Looking up /var/folders/d0/5b415g_d1nld6ygg0sbqvsv40000gn/T/tmp_Vq_AN\r\ndebug3: Sent message fd 8 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673/apt.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:20359\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 32768 bytes at 32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 6 20359 bytes at 65536\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2200 -o 'IdentityFile="/Users/education/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/education/.ansible/cp/17d6e21220 127.0.0.1 '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673/ /home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673/apt.py && sleep 0'"'"''
<127.0.0.1> (0, '', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 68578\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2200 -o 'IdentityFile="/Users/education/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/education/.ansible/cp/17d6e21220 -tt 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-avycbpblsdpwpbbwxrahvffszcdocuut; /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673/apt.py; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1500347705.21-36095657481673/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<127.0.0.1> (0, '\r\n{"stdout": "Reading package lists...\\nBuilding dependency tree...\\nReading state information...\\nThe following packages were automatically installed and are no longer required:\\n  python-crypto python-ecdsa python-httplib2 python-jinja2 python-markupsafe\\n  python-paramiko python-pkg-resources python-setuptools python-six\\n  python-yaml sshpass\\nUse \'sudo apt autoremove\' to remove them.\\nThe following additional packages will be installed:\\n  daemon\\nThe following NEW packages will be installed:\\n  daemon jenkins\\n0 upgraded, 2 newly installed, 0 to remove and 73 not upgraded.\\nNeed to get 72.5 MB of archives.\\nAfter this operation, 73.1 MB of additional disk space will be used.\\nGet:1 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 daemon amd64 0.6.4-1 [98.2 kB]\\nGet:2 https://pkg.jenkins.io/debian binary/ jenkins 2.70 [72.4 MB]\\nFetched 72.5 MB in 4min 34s (264 kB/s)\\nSelecting previously unselected package daemon.\\r\\n(Reading database ... \\r(Reading database ... 5%\\r(Reading database ... 10%\\r(Reading database ... 15%\\r(Reading database ... 20%\\r(Reading database ... 25%\\r(Reading database ... 30%\\r(Reading database ... 35%\\r(Reading database ... 40%\\r(Reading database ... 45%\\r(Reading database ... 50%\\r(Reading database ... 55%\\r(Reading database ... 60%\\r(Reading database ... 65%\\r(Reading database ... 70%\\r(Reading database ... 75%\\r(Reading database ... 80%\\r(Reading database ... 85%\\r(Reading database ... 90%\\r(Reading database ... 95%\\r(Reading database ... 100%\\r(Reading database ... 70598 files and directories currently installed.)\\r\\nPreparing to unpack .../daemon_0.6.4-1_amd64.deb ...\\r\\nUnpacking daemon (0.6.4-1) ...\\r\\nSelecting previously unselected package jenkins.\\r\\nPreparing to unpack .../archives/jenkins_2.70_all.deb ...\\r\\nUnpacking jenkins (2.70) ...\\r\\nProcessing triggers for man-db (2.7.5-1) ...\\r\\nProcessing triggers for systemd (229-4ubuntu17) ...\\r\\nProcessing triggers for ureadahead (0.100.0-19) ...\\r\\nSetting up daemon (0.6.4-1) ...\\r\\nSetting up jenkins (2.70) ...\\r\\nProcessing triggers for systemd (229-4ubuntu17) ...\\r\\nProcessing triggers for ureadahead (0.100.0-19) ...\\r\\n", "cache_updated": false, "changed": true, "stderr": "", "invocation": {"module_args": {"dpkg_options": "force-confdef,force-confold", "upgrade": null, "force": false, "name": "jenkins", "package": ["jenkins"], "purge": false, "allow_unauthenticated": false, "state": "present", "autoremove": null, "update_cache": null, "default_release": null, "only_upgrade": false, "cache_valid_time": 0, "deb": null, "install_recommends": null}}, "diff": {}, "cache_update_time": 1500347705}\r\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 68578\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 127.0.0.1 closed.\r\n')
ERROR! Unexpected Exception: 'a45e60e1-1259-9e84-709a-0000000029af'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/Library/Python/2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/Library/Python/2.7/site-packages/ansible/executor/playbook_executor.py", line 153, in run
    result = self._tqm.run(play=play)
  File "/Library/Python/2.7/site-packages/ansible/executor/task_queue_manager.py", line 284, in run
    play_return = strategy.run(iterator, play_context)
  File "/Library/Python/2.7/site-packages/ansible/plugins/strategy/linear.py", line 278, in run
    results += self._wait_on_pending_results(iterator)
  File "/Library/Python/2.7/site-packages/ansible/plugins/strategy/__init__.py", line 574, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/Library/Python/2.7/site-packages/ansible/plugins/strategy/__init__.py", line 446, in _process_pending_results
    if original_host not in self._notified_handlers[target_handler._uuid]:
KeyError: 'a45e60e1-1259-9e84-709a-0000000029af'
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by geerlingguy** [comment]
@fubarhouse - I just did a test build with my Ubuntu 16.04 Vagrant box and the example Vagrant setup in ansible-vagrant-examples (https://github.com/geerlingguy/ansible-vagrant-examples/tree/master/jenkins), and it seems everything ran correctly.

It seems there is some sort of SSH connection problem, judging by the error messages:

```
debug3: mux_client_read_packet: read header failed: Broken pipe
```

and 

```
KeyError: 'a45e60e1-1259-9e84-709a-0000000029af'
```

But it's kind of hard for me to figure out what might be going wrong. It looks like it's at least trying to install `daemon` and `jenkins`.

If you use the ansible-vagrant-examples jenkins example linked above, does that fail the same way / on the same task?
