### ISSUE TITLE
provision for setting jnlp port.

### ISSUE THREAD

**Issue by bhanuvrat** [geerlingguy/ansible-role-jenkins#29]
the role is unable to install jenkins-plugins because jnlp port is not configured.
A blog bost by voidtech [1], helps solve the issue but requires manual step which I am unable to automate via ansible.

```
TASK: [geerlingguy.jenkins | Install Jenkins plugins.] ************************
failed: [ci-server1] => (item=git) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://X.Y.Z.W:8080/", "install-plugin", "git"], "delta": "0:00:03.872323", "end": "2015-10-26 17:45:50.800905", "item": "git", "rc": 255, "start": "2015-10-26 17:45:46.928582", "warnings": []}
stderr: Oct 26, 2015 5:45:50 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel Chunked connection to http://X.Y.Z.W:8080/cli
java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

hudson.remoting.RequestAbortedException: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at hudson.remoting.Request.abort(Request.java:297)
    at hudson.remoting.Channel.terminate(Channel.java:844)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:69)
    at ......remote call to Chunked connection to http://X.Y.Z.W:8080/cli(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1413)
    at hudson.remoting.Request.call(Request.java:172)
    at hudson.remoting.Channel.call(Channel.java:777)
    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:250)
    at hudson.remoting.$Proxy1.waitForProperty(Unknown Source)
    at hudson.remoting.Channel.waitForRemoteProperty(Channel.java:1255)
    at hudson.cli.CLI.<init>(CLI.java:147)
    at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
    at hudson.cli.CLI._main(CLI.java:479)
    at hudson.cli.CLI.main(CLI.java:390)
Caused by: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
failed: [ci-server1] => (item=sonar) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://X.Y.Z.W:8080/", "install-plugin", "sonar"], "delta": "0:00:03.513631", "end": "2015-10-26 17:45:54.961781", "item": "sonar", "rc": 255, "start": "2015-10-26 17:45:51.448150", "warnings": []}
stderr: Oct 26, 2015 5:45:54 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel Chunked connection to http://X.Y.Z.W:8080/cli
java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

hudson.remoting.RequestAbortedException: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at hudson.remoting.Request.abort(Request.java:297)
    at hudson.remoting.Channel.terminate(Channel.java:844)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:69)
    at ......remote call to Chunked connection to http://X.Y.Z.W:8080/cli(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1413)
    at hudson.remoting.Request.call(Request.java:172)
    at hudson.remoting.Channel.call(Channel.java:777)
    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:250)
    at hudson.remoting.$Proxy1.waitForProperty(Unknown Source)
    at hudson.remoting.Channel.waitForRemoteProperty(Channel.java:1255)
    at hudson.cli.CLI.<init>(CLI.java:147)
    at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
    at hudson.cli.CLI._main(CLI.java:479)
    at hudson.cli.CLI.main(CLI.java:390)
Caused by: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
failed: [ci-server1] => (item=ssh) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://X.Y.Z.W:8080/", "install-plugin", "ssh"], "delta": "0:00:03.467868", "end": "2015-10-26 17:46:00.109269", "item": "ssh", "rc": 255, "start": "2015-10-26 17:45:56.641401", "warnings": []}
stderr: Oct 26, 2015 5:46:00 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel Chunked connection to http://X.Y.Z.W:8080/cli
java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

hudson.remoting.RequestAbortedException: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at hudson.remoting.Request.abort(Request.java:297)
    at hudson.remoting.Channel.terminate(Channel.java:844)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:69)
    at ......remote call to Chunked connection to http://X.Y.Z.W:8080/cli(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1413)
    at hudson.remoting.Request.call(Request.java:172)
    at hudson.remoting.Channel.call(Channel.java:777)
    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:250)
    at hudson.remoting.$Proxy1.waitForProperty(Unknown Source)
    at hudson.remoting.Channel.waitForRemoteProperty(Channel.java:1255)
    at hudson.cli.CLI.<init>(CLI.java:147)
    at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
    at hudson.cli.CLI._main(CLI.java:479)
    at hudson.cli.CLI.main(CLI.java:390)
Caused by: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
failed: [ci-server1] => (item=github) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://X.Y.Z.W:8080/", "install-plugin", "github"], "delta": "0:00:03.372999", "end": "2015-10-26 17:46:04.243199", "item": "github", "rc": 255, "start": "2015-10-26 17:46:00.870200", "warnings": []}
stderr: Oct 26, 2015 5:46:04 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel Chunked connection to http://X.Y.Z.W:8080/cli
java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

hudson.remoting.RequestAbortedException: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at hudson.remoting.Request.abort(Request.java:297)
    at hudson.remoting.Channel.terminate(Channel.java:844)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:69)
    at ......remote call to Chunked connection to http://X.Y.Z.W:8080/cli(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1413)
    at hudson.remoting.Request.call(Request.java:172)
    at hudson.remoting.Channel.call(Channel.java:777)
    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:250)
    at hudson.remoting.$Proxy1.waitForProperty(Unknown Source)
    at hudson.remoting.Channel.waitForRemoteProperty(Channel.java:1255)
    at hudson.cli.CLI.<init>(CLI.java:147)
    at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
    at hudson.cli.CLI._main(CLI.java:479)
    at hudson.cli.CLI.main(CLI.java:390)
Caused by: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

FATAL: all hosts have already failed -- aborting
```

[1] https://voidtech.wordpress.com/2015/08/26/jenkins-cli-jar-java-io-streamcorruptedexception-invalid-stream-header-0a0a0a0a-solution/

**Comment by stuart-warren** [comment]
Create a /var/lib/jenkins/init.groovy.d/jnlp-port.groovy file before startup (or restart jenkins)

https://github.com/jenkinsci/docker/blob/master/init.groovy

**Comment by olo-dw** [comment]
Are you sure he jnlp port is always mandatory?
