### ISSUE TITLE
CI failing with 'service did not take the steps required by its unit configuration'

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-jenkins#361]
```
TASK [geerlingguy.jenkins : Modify variables in init file.] ********************
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:216)
  changed: [instance] => (item={'option': 'JENKINS_OPTS', 'value': ''})
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:217)
  changed: [instance] => (item={'option': 'JAVA_OPTS', 'value': '-Djenkins.install.runSetupWizard=false'})
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:218)
  changed: [instance] => (item={'option': 'JENKINS_HOME', 'value': '/var/lib/jenkins'})
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:219)
  changed: [instance] => (item={'option': 'JENKINS_PREFIX', 'value': ''})
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:220)
  changed: [instance] => (item={'option': 'JENKINS_PORT', 'value': 8080})
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:221)
  
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:222)
  TASK [geerlingguy.jenkins : Ensure jenkins_home /var/lib/jenkins exists.] ******
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:223)
  ok: [instance]
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:224)
  
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:225)
  TASK [geerlingguy.jenkins : Immediately restart Jenkins on init config changes.] ***
(https://github.com/geerlingguy/ansible-role-jenkins/runs/8094535048?check_suite_focus=true#step:5:226)
  fatal: [instance]: FAILED! => {"changed": false, "msg": "Unable to start service jenkins: Job for jenkins.service failed because the service did not take the steps required by its unit configuration.\nSee \"systemctl status jenkins.service\" and \"journalctl -xe\" for details.\n"}
```

**Comment by geerlingguy** [comment]
Ah... at least on Rocky Linux it's a Java minimum version issue:

```
Aug 30 14:44:28 instance systemd[1]: Starting Jenkins Continuous Integration Server...
░░ Subject: A start job for unit jenkins.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit jenkins.service has begun execution.
░░ 
░░ The job identifier is 385.
Aug 30 14:44:28 instance jenkins[5832]: Aug 30, 2022 2:44:28 PM executable.Main verifyJavaVersion
Aug 30 14:44:28 instance jenkins[5832]: SEVERE: Running with Java class version 52, which is older than the Minimum required version 55. See https://jenkins.io/redirect/java-support/
Aug 30 14:44:28 instance jenkins[5832]: java.lang.UnsupportedClassVersionError: 52.0
Aug 30 14:44:28 instance jenkins[5832]:         at executable.Main.verifyJavaVersion(Main.java:145)
Aug 30 14:44:28 instance jenkins[5832]:         at executable.Main.main(Main.java:109)
Aug 30 14:44:28 instance jenkins[5832]: Jenkins requires Java versions [17, 11] but you are running with Java 1.8 from /usr/lib/jvm/java-8-openjdk-arm64/jre
Aug 30 14:44:28 instance jenkins[5832]: java.lang.UnsupportedClassVersionError: 52.0
Aug 30 14:44:28 instance jenkins[5832]:         at executable.Main.verifyJavaVersion(Main.java:145)
Aug 30 14:44:28 instance jenkins[5832]:         at executable.Main.main(Main.java:109)
Aug 30 14:44:28 instance systemd[1]: jenkins.service: Failed with result 'protocol'.
░░ Subject: Unit failed
```

**Comment by geerlingguy** [comment]
Looks like I shouldn't be using OpenJDK 8 anymore, going to drop the testing defaults so it uses the java role defaults (Java 11 or Java 17 on the latest releases).

**Comment by geerlingguy** [comment]
Fixed!
